export const COLORS = {
  MAIN_YELLOW_PRIMARY: "#ECCE74",
  MAIN_YELLOW_SECONDARY: "#E5BE48",
  TEXT_DEFAULT: "#56331F",
  BACKGROUND_DEFAULT: "#FFFFFF",
  LIGHT_GREY: "#F1F1F1",
  DARK_GREY: "#D6D6D6"
};
